In [44]:
import numpy as np
x = np.array([[2],[1]])
y = np.array([[1],[2],[3]])
prob = np.array([[0.4,0.14,0.05],[0.02,0.26,0.13]])
print(x)
print(y)
print(prob)

[[2]
 [1]]
[[1]
 [2]
 [3]]
[[0.4  0.14 0.05]
 [0.02 0.26 0.13]]


In [45]:
probSum =np.sum(prob)
print('total probability ist', probSum)

total probability ist 1.0


In [42]:
xProb = np.sum(p,axis=1)
yProb = np.sum(p,axis=0)
print('x marginal probalility',xProb)
print('y marginal probalility',yProb)

yProbXequals2 = p[0]/xProb[0]
print('y probalility under condition x = 2 is',yProbXequals2)

EyXequals2 = np.dot(yProbXequals2,y)
print('y expectation under condition x = 2 is', EyXequals2)

x marginal probalility [0.59 0.41]
x marginal probalility [0.42 0.4  0.18]
y probalility under condition x = 2 is [0.6779661  0.23728814 0.08474576]
y expectation under condition x = 2 is [1.40677966]


In [49]:
x1ProbYequals3 = prob[1][2]/yProbability[2]
print('x=1 under condition y = 3 is', x1ProbYequals3)

x=1 under condition y = 3 is 0.7222222222222223


In [56]:
from scipy import integrate
def f1(x, y):
    return 1
v, err = integrate.dblquad(f1, 0, 1, 0, 0.5)
print('total probability ist', v)

total probability ist 0.5


In [61]:
def f3(x):
    return (2*x+4*0.5)/15
v1, err = integrate.quad(f3, 0, 2)
print(v)

0.5333333333333334


In [62]:
def f3(x):
    return (2*x+4*0.5)/15
v2, err = integrate.quad(f3, 0, 3)
print(v2)

1.0
