In [2]:
import numpy as np

In [5]:
n = np.random.rand(8)

In [6]:
print(n)

[0.4884323  0.76125091 0.79387671 0.85858456 0.96639785 0.93496948
 0.73751528 0.78704589]


索引 [Start,End (not included),Jump]

In [ ]:
n_odd = n[1::2]    #index syntax start:end(not included):jup
print(n_odd)

In [8]:
n_rev = n[::-1]
print(n_rev)

[0.78704589 0.73751528 0.93496948 0.96639785 0.85858456 0.79387671
 0.76125091 0.4884323 ]


对索引矩阵操作，改变原矩阵

In [9]:
a = np.array([1,2,3,4,5])
b = a[1:4]
b[0]=200
print(a[1])
a

200


array([  1, 200,   3,   4,   5])

In [10]:
m = np.random.rand(3,4)
print(m)
print(m.shape)

[[0.70536247 0.08323638 0.42333316 0.42640823]
 [0.67871533 0.20825858 0.56689248 0.78261989]
 [0.74063319 0.91470064 0.35296082 0.8731998 ]]
(3, 4)


In [11]:
m_revrowel = m[:,::-1] #all rows, reverse column 
print(m_revrowel)

[[0.42640823 0.42333316 0.08323638 0.70536247]
 [0.78261989 0.56689248 0.20825858 0.67871533]
 [0.8731998  0.35296082 0.91470064 0.74063319]]


In [12]:
m_revall = m[::-1, ::-1]
print(m_revall)

[[0.8731998  0.35296082 0.91470064 0.74063319]
 [0.78261989 0.56689248 0.20825858 0.67871533]
 [0.42640823 0.42333316 0.08323638 0.70536247]]


In [13]:
print(m.T) #transpose

[[0.70536247 0.67871533 0.74063319]
 [0.08323638 0.20825858 0.91470064]
 [0.42333316 0.56689248 0.35296082]
 [0.42640823 0.78261989 0.8731998 ]]


In [14]:
m_cut_temp = m[(0,-1),:]  #first last row
print(m_cut_temp)

m_cut = m_cut_temp[:,(0,-1)]  #first last column
print(m_cut)

m_cut_direct = m[(0,-1),:][:,(0,-1)] 
print (m_cut_direct)

[[0.70536247 0.08323638 0.42333316 0.42640823]
 [0.74063319 0.91470064 0.35296082 0.8731998 ]]
[[0.70536247 0.42640823]
 [0.74063319 0.8731998 ]]
[[0.70536247 0.42640823]
 [0.74063319 0.8731998 ]]


In [15]:
m[[0,-1],[0,-1]]    #2 outputs:(0,0) and (-1,-1)

array([0.70536247, 0.8731998 ])

In [23]:
print(m)
m[[0],[-1]]

[[0.70536247 0.08323638 0.42333316 0.42640823]
 [0.67871533 0.20825858 0.56689248 0.78261989]
 [0.74063319 0.91470064 0.35296082 0.8731998 ]]


array([0.42640823])

In [32]:
m[[[0],[-1]],[[0],[-1]]]

array([[0.70536247],
       [0.8731998 ]])

In [34]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  
print(x)
print (y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [36]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]     #行1到行2，不包括行3 ； 列1到列2，不包括列3
c = a[1:3,[1,2]]
d = a[...,1:]      #所有行，列1到最后
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [39]:
x=np.arange(32).reshape((8,4))
print(x)                #花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。
print (x[[4,2,1,7]])    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


In [53]:
a = np.array([[1,2,3], [4,5,6]])
aa = np.reshape(a, 6)

In [49]:
a = np.random.rand(5)               #rank 1 vermeiden 
print(a)
print(a.shape)
print(a.T)
print(a.dot(a.T))

[0.8455698  0.13212028 0.29510353 0.49384695 0.75861973]
(5,)
[0.8455698  0.13212028 0.29510353 0.49384695 0.75861973]
1.6389188544396847


In [51]:
a = np.random.rand(5,1)
print(a)

[[0.81998239]
 [0.38882836]
 [0.50620935]
 [0.5320402 ]
 [0.9225436 ]]


In [52]:
a = np.random.rand(1,5)
print(a)

[[0.63364514 0.59665111 0.81243283 0.17140145 0.05838773]]


In [4]:
a = np.arange(5)

In [5]:
print(a)

[0 1 2 3 4]


In [9]:
b = a[:,None]**np.arange(1+4)
print(b)

c = a[:,None]**np.arange(1,4,1)
print(c)

[[  1   0   0   0   0]
 [  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]
[[ 0  0  0]
 [ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]
 [ 4 16 64]]
